unit TestRetornaLitros;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uAbastecimento_Interface, uAbastecimento, System.SysUtils,
  Vcl.Dialogs, System.TypInfo, System.Classes, System.Math;

type
  // Test methods for class TAbastecimento

  TestTAbastecimento = class(TTestCase)
  strict private
    FAbastecimento: TAbastecimento;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRetornaLitros;
  end;

implementation

procedure TestTAbastecimento.SetUp;
begin
  FAbastecimento := TAbastecimento.Create;
end;

procedure TestTAbastecimento.TearDown;
begin
  FAbastecimento.Free;
  FAbastecimento := nil;
end;

procedure TestTAbastecimento.TestRetornaLitros;
var
  ReturnValue: Double;
  pTanque: TTanque;
  pValor: Double;
begin
  // TODO: Setup method call parameters
  pValor := 5.80;
  pTanque := tGasolina;
  ReturnValue := FAbastecimento.RetornaLitros(pValor, pTanque);
  // TODO: Validate method results
  CheckEquals(1, ReturnValue, 'Ocorreu um erro na função RetornaLitros!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAbastecimento.Suite);
end.

